#!/bin/sh

set -e

echo "Launching the 'cat runtime'..."
echo "Starting application: cat /tmp/myapp/*"

cat /tmp/myapp/*

echo "Well, that was exhausting! Sleeping..."
while true; do sleep 1; echo -n .;done
